
export default {
  "light": {
    "ambcrypto": require('./../assets/images/source_logos/ambcrypto_light.png'),
    "coindesk": require('./../assets/images/source_logos/coindesk_light.png'),
    "coinnounce": require('./../assets/images/source_logos/coinnounce_light.png'),
    "cointelegraph": require('./../assets/images/source_logos/cointelegraph_light.png'),
    "cryptobriefing": require('./../assets/images/source_logos/cryptobriefing_light.png'),
    "cryptodaily": require('./../assets/images/source_logos/cryptodaily_light.png'),
    "decrypt": require('./../assets/images/source_logos/decrypt_light.png'),
    "utoday": require('./../assets/images/source_logos/utoday_light.png'),
    "bitcoin": require('./../assets/images/source_logos/bitcoin_light.png'),
    "theblock": require('./../assets/images/source_logos/theblock_light.png'),
    "blockchainnews": require('./../assets/images/source_logos/blockchainnews_light.png'),
    "thedailychain": require('./../assets/images/source_logos/thedailychain_light.png'),
    "bitcoinist": require('./../assets/images/source_logos/bitcoinist_light.png'),
    "newsbtc": require('./../assets/images/source_logos/newsbtc_light.png'),
    "coingape": require('./../assets/images/source_logos/coingape_light.png'),
    "cryptomode": require('./../assets/images/source_logos/cryptomode_light.png'),
    "medium": require('./../assets/images/source_logos/medium_light.png'),
    "twitter": require('./../assets/images/source_logos/twitter_light.png'),
    "thedailyhodl": require('./../assets/images/source_logos/thedailyhodl_light.png'),
    "cryptopotato": require('./../assets/images/source_logos/cryptopotato_light.png'),
  },
  "dark": {
    "ambcrypto": require('./../assets/images/source_logos/ambcrypto_dark.png'),
    "coindesk": require('./../assets/images/source_logos/coindesk_dark.png'),
    "coinnounce": require('./../assets/images/source_logos/coinnounce_dark.png'),
    "cointelegraph": require('./../assets/images/source_logos/cointelegraph_dark.png'),
    "cryptobriefing": require('./../assets/images/source_logos/cryptobriefing_dark.png'),
    "cryptodaily": require('./../assets/images/source_logos/cryptodaily_dark.png'),
    "decrypt": require('./../assets/images/source_logos/decrypt_dark.png'),
    "utoday": require('./../assets/images/source_logos/utoday_dark.png'),
    "bitcoin": require('./../assets/images/source_logos/bitcoin_dark.png'),
    "theblock": require('./../assets/images/source_logos/theblock_dark.png'),
    "blockchainnews": require('./../assets/images/source_logos/blockchainnews_dark.png'),
    "thedailychain": require('./../assets/images/source_logos/thedailychain_dark.png'),
    "bitcoinist": require('./../assets/images/source_logos/bitcoinist_dark.png'),
    "newsbtc": require('./../assets/images/source_logos/newsbtc_dark.png'),
    "coingape": require('./../assets/images/source_logos/coingape_dark.png'),
    "cryptomode": require('./../assets/images/source_logos/cryptomode_dark.png'),
    "medium": require('./../assets/images/source_logos/medium_dark.png'),
    "twitter": require('./../assets/images/source_logos/twitter_dark.png'),
    "thedailyhodl": require('./../assets/images/source_logos/thedailyhodl_dark.png'),
    "cryptopotato": require('./../assets/images/source_logos/cryptopotato_dark.png'),
  }
};
